/*
 * Ollama API
 * API Spec for Ollama API. Please see https://github.com/jmorganca/ollama/blob/main/docs/api.md for more details.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.ollama.client.api;

import ch.lianto.ollama.client.model.GenerateCompletionRequest;
import ch.lianto.ollama.client.model.GenerateCompletionResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for CompletionsApi
 */
@Ignore
public class CompletionsApiTest {

    private final CompletionsApi api = new CompletionsApi();

    
    /**
     * Generate a response for a given prompt with a provided model.
     *
     * The final response object will include statistics and additional data from the request.
     */
    @Test
    public void generateCompletionTest()  {
        GenerateCompletionRequest generateCompletionRequest = null;
        GenerateCompletionResponse response = api.generateCompletion(generateCompletionRequest).block();

        // TODO: test validations
    }
    
}
