/*
 * Ollama API
 * API Spec for Ollama API. Please see https://github.com/jmorganca/ollama/blob/main/docs/api.md for more details.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.ollama.client.api;

import ch.lianto.ollama.client.model.GenerateEmbeddingRequest;
import ch.lianto.ollama.client.model.GenerateEmbeddingResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for EmbeddingsApi
 */
@Ignore
public class EmbeddingsApiTest {

    private final EmbeddingsApi api = new EmbeddingsApi();

    
    /**
     * Generate embeddings from a model.
     *
     * 
     */
    @Test
    public void generateEmbeddingTest()  {
        GenerateEmbeddingRequest generateEmbeddingRequest = null;
        GenerateEmbeddingResponse response = api.generateEmbedding(generateEmbeddingRequest).block();

        // TODO: test validations
    }
    
}
