/*
 * Ollama API
 * API Spec for Ollama API. Please see https://github.com/jmorganca/ollama/blob/main/docs/api.md for more details.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.ollama.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GenerateCompletionResponse
 */
public class GenerateCompletionResponseTest {
    private final GenerateCompletionResponse model = new GenerateCompletionResponse();

    /**
     * Model tests for GenerateCompletionResponse
     */
    @Test
    public void testGenerateCompletionResponse() {
        // TODO: test GenerateCompletionResponse
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'done'
     */
    @Test
    public void doneTest() {
        // TODO: test done
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'totalDuration'
     */
    @Test
    public void totalDurationTest() {
        // TODO: test totalDuration
    }

    /**
     * Test the property 'loadDuration'
     */
    @Test
    public void loadDurationTest() {
        // TODO: test loadDuration
    }

    /**
     * Test the property 'promptEvalCount'
     */
    @Test
    public void promptEvalCountTest() {
        // TODO: test promptEvalCount
    }

    /**
     * Test the property 'promptEvalDuration'
     */
    @Test
    public void promptEvalDurationTest() {
        // TODO: test promptEvalDuration
    }

    /**
     * Test the property 'evalCount'
     */
    @Test
    public void evalCountTest() {
        // TODO: test evalCount
    }

    /**
     * Test the property 'evalDuration'
     */
    @Test
    public void evalDurationTest() {
        // TODO: test evalDuration
    }

}
