/*
 * Ollama API
 * API Spec for Ollama API. Please see https://github.com/jmorganca/ollama/blob/main/docs/api.md for more details.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.ollama.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GenerateEmbeddingResponse
 */
public class GenerateEmbeddingResponseTest {
    private final GenerateEmbeddingResponse model = new GenerateEmbeddingResponse();

    /**
     * Model tests for GenerateEmbeddingResponse
     */
    @Test
    public void testGenerateEmbeddingResponse() {
        // TODO: test GenerateEmbeddingResponse
    }

    /**
     * Test the property 'embedding'
     */
    @Test
    public void embeddingTest() {
        // TODO: test embedding
    }

}
