/*
 * Ollama API
 * API Spec for Ollama API. Please see https://github.com/jmorganca/ollama/blob/main/docs/api.md for more details.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.ollama.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PushModelStatus
 */
public class PushModelStatusTest {
    /**
     * Model tests for PushModelStatus
     */
    @Test
    public void testPushModelStatus() {
        // TODO: test PushModelStatus
    }

}
