/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import ch.lianto.openai.client.model.ChatCompletionNamedToolChoice;
import ch.lianto.openai.client.model.ChatCompletionNamedToolChoiceFunction;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ChatCompletionToolChoiceOption
 */
public class ChatCompletionToolChoiceOptionTest {
    private final ChatCompletionToolChoiceOption model = new ChatCompletionToolChoiceOption();

    /**
     * Model tests for ChatCompletionToolChoiceOption
     */
    @Test
    public void testChatCompletionToolChoiceOption() {
        // TODO: test ChatCompletionToolChoiceOption
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'function'
     */
    @Test
    public void functionTest() {
        // TODO: test function
    }

}
