/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import ch.lianto.openai.client.model.ChatCompletionMessageToolCall;
import ch.lianto.openai.client.model.ChatCompletionRequestAssistantMessage;
import ch.lianto.openai.client.model.ChatCompletionRequestAssistantMessageFunctionCall;
import ch.lianto.openai.client.model.ChatCompletionRequestFunctionMessage;
import ch.lianto.openai.client.model.ChatCompletionRequestSystemMessage;
import ch.lianto.openai.client.model.ChatCompletionRequestToolMessage;
import ch.lianto.openai.client.model.ChatCompletionRequestUserMessage;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ChatCompletionRequestMessage
 */
public class ChatCompletionRequestMessageTest {
    private final ChatCompletionRequestMessage model = new ChatCompletionRequestMessage();

    /**
     * Model tests for ChatCompletionRequestMessage
     */
    @Test
    public void testChatCompletionRequestMessage() {
        // TODO: test ChatCompletionRequestMessage
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'toolCalls'
     */
    @Test
    public void toolCallsTest() {
        // TODO: test toolCalls
    }

    /**
     * Test the property 'functionCall'
     */
    @Test
    public void functionCallTest() {
        // TODO: test functionCall
    }

    /**
     * Test the property 'toolCallId'
     */
    @Test
    public void toolCallIdTest() {
        // TODO: test toolCallId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
