/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import ch.lianto.openai.client.model.ChatCompletionFunctionCallOption;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateChatCompletionRequestFunctionCall
 */
public class CreateChatCompletionRequestFunctionCallTest {
    private final CreateChatCompletionRequestFunctionCall model = new CreateChatCompletionRequestFunctionCall();

    /**
     * Model tests for CreateChatCompletionRequestFunctionCall
     */
    @Test
    public void testCreateChatCompletionRequestFunctionCall() {
        // TODO: test CreateChatCompletionRequestFunctionCall
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
