/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import ch.lianto.openai.client.model.CreateFineTuneRequestHyperparameters;
import ch.lianto.openai.client.model.CreateFineTuneRequestModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateFineTuneRequest
 */
public class CreateFineTuneRequestTest {
    private final CreateFineTuneRequest model = new CreateFineTuneRequest();

    /**
     * Model tests for CreateFineTuneRequest
     */
    @Test
    public void testCreateFineTuneRequest() {
        // TODO: test CreateFineTuneRequest
    }

    /**
     * Test the property 'trainingFile'
     */
    @Test
    public void trainingFileTest() {
        // TODO: test trainingFile
    }

    /**
     * Test the property 'batchSize'
     */
    @Test
    public void batchSizeTest() {
        // TODO: test batchSize
    }

    /**
     * Test the property 'classificationBetas'
     */
    @Test
    public void classificationBetasTest() {
        // TODO: test classificationBetas
    }

    /**
     * Test the property 'classificationNClasses'
     */
    @Test
    public void classificationNClassesTest() {
        // TODO: test classificationNClasses
    }

    /**
     * Test the property 'classificationPositiveClass'
     */
    @Test
    public void classificationPositiveClassTest() {
        // TODO: test classificationPositiveClass
    }

    /**
     * Test the property 'computeClassificationMetrics'
     */
    @Test
    public void computeClassificationMetricsTest() {
        // TODO: test computeClassificationMetrics
    }

    /**
     * Test the property 'hyperparameters'
     */
    @Test
    public void hyperparametersTest() {
        // TODO: test hyperparameters
    }

    /**
     * Test the property 'learningRateMultiplier'
     */
    @Test
    public void learningRateMultiplierTest() {
        // TODO: test learningRateMultiplier
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'promptLossWeight'
     */
    @Test
    public void promptLossWeightTest() {
        // TODO: test promptLossWeight
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    public void suffixTest() {
        // TODO: test suffix
    }

    /**
     * Test the property 'validationFile'
     */
    @Test
    public void validationFileTest() {
        // TODO: test validationFile
    }

}
