/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import ch.lianto.openai.client.model.FineTuneEvent;
import ch.lianto.openai.client.model.FineTuneHyperparams;
import ch.lianto.openai.client.model.OpenAIFile;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for FineTune
 */
public class FineTuneTest {
    private final FineTune model = new FineTune();

    /**
     * Model tests for FineTune
     */
    @Test
    public void testFineTune() {
        // TODO: test FineTune
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

    /**
     * Test the property 'fineTunedModel'
     */
    @Test
    public void fineTunedModelTest() {
        // TODO: test fineTunedModel
    }

    /**
     * Test the property 'hyperparams'
     */
    @Test
    public void hyperparamsTest() {
        // TODO: test hyperparams
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    public void organizationIdTest() {
        // TODO: test organizationId
    }

    /**
     * Test the property 'resultFiles'
     */
    @Test
    public void resultFilesTest() {
        // TODO: test resultFiles
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'trainingFiles'
     */
    @Test
    public void trainingFilesTest() {
        // TODO: test trainingFiles
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'validationFiles'
     */
    @Test
    public void validationFilesTest() {
        // TODO: test validationFiles
    }

}
