/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for FineTuneHyperparams
 */
public class FineTuneHyperparamsTest {
    private final FineTuneHyperparams model = new FineTuneHyperparams();

    /**
     * Model tests for FineTuneHyperparams
     */
    @Test
    public void testFineTuneHyperparams() {
        // TODO: test FineTuneHyperparams
    }

    /**
     * Test the property 'batchSize'
     */
    @Test
    public void batchSizeTest() {
        // TODO: test batchSize
    }

    /**
     * Test the property 'classificationNClasses'
     */
    @Test
    public void classificationNClassesTest() {
        // TODO: test classificationNClasses
    }

    /**
     * Test the property 'classificationPositiveClass'
     */
    @Test
    public void classificationPositiveClassTest() {
        // TODO: test classificationPositiveClass
    }

    /**
     * Test the property 'computeClassificationMetrics'
     */
    @Test
    public void computeClassificationMetricsTest() {
        // TODO: test computeClassificationMetrics
    }

    /**
     * Test the property 'learningRateMultiplier'
     */
    @Test
    public void learningRateMultiplierTest() {
        // TODO: test learningRateMultiplier
    }

    /**
     * Test the property 'nEpochs'
     */
    @Test
    public void nEpochsTest() {
        // TODO: test nEpochs
    }

    /**
     * Test the property 'promptLossWeight'
     */
    @Test
    public void promptLossWeightTest() {
        // TODO: test promptLossWeight
    }

}
