/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import ch.lianto.openai.client.model.SubmitToolOutputsRunRequestToolOutputsInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for SubmitToolOutputsRunRequest
 */
public class SubmitToolOutputsRunRequestTest {
    private final SubmitToolOutputsRunRequest model = new SubmitToolOutputsRunRequest();

    /**
     * Model tests for SubmitToolOutputsRunRequest
     */
    @Test
    public void testSubmitToolOutputsRunRequest() {
        // TODO: test SubmitToolOutputsRunRequest
    }

    /**
     * Test the property 'toolOutputs'
     */
    @Test
    public void toolOutputsTest() {
        // TODO: test toolOutputs
    }

}
