/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import java.util.Objects;
import java.util.Arrays;
import ch.lianto.openai.client.model.MessageFileObject;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ListMessageFilesResponse
 */
@JsonPropertyOrder({
  ListMessageFilesResponse.JSON_PROPERTY_OBJECT,
  ListMessageFilesResponse.JSON_PROPERTY_DATA,
  ListMessageFilesResponse.JSON_PROPERTY_FIRST_ID,
  ListMessageFilesResponse.JSON_PROPERTY_LAST_ID,
  ListMessageFilesResponse.JSON_PROPERTY_HAS_MORE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-08T23:05:52.228713843+01:00[Europe/Zurich]")
public class ListMessageFilesResponse {
  public static final String JSON_PROPERTY_OBJECT = "object";
  private String _object;

  public static final String JSON_PROPERTY_DATA = "data";
  private List<MessageFileObject> data = new ArrayList<>();

  public static final String JSON_PROPERTY_FIRST_ID = "first_id";
  private String firstId;

  public static final String JSON_PROPERTY_LAST_ID = "last_id";
  private String lastId;

  public static final String JSON_PROPERTY_HAS_MORE = "has_more";
  private Boolean hasMore;

  public ListMessageFilesResponse() {
  }

  public ListMessageFilesResponse _object(String _object) {
    
    this._object = _object;
    return this;
  }

   /**
   * Get _object
   * @return _object
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getObject() {
    return _object;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(String _object) {
    this._object = _object;
  }


  public ListMessageFilesResponse data(List<MessageFileObject> data) {
    
    this.data = data;
    return this;
  }

  public ListMessageFilesResponse addDataItem(MessageFileObject dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<MessageFileObject> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(List<MessageFileObject> data) {
    this.data = data;
  }


  public ListMessageFilesResponse firstId(String firstId) {
    
    this.firstId = firstId;
    return this;
  }

   /**
   * Get firstId
   * @return firstId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirstId() {
    return firstId;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstId(String firstId) {
    this.firstId = firstId;
  }


  public ListMessageFilesResponse lastId(String lastId) {
    
    this.lastId = lastId;
    return this;
  }

   /**
   * Get lastId
   * @return lastId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastId() {
    return lastId;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastId(String lastId) {
    this.lastId = lastId;
  }


  public ListMessageFilesResponse hasMore(Boolean hasMore) {
    
    this.hasMore = hasMore;
    return this;
  }

   /**
   * Get hasMore
   * @return hasMore
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HAS_MORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getHasMore() {
    return hasMore;
  }


  @JsonProperty(JSON_PROPERTY_HAS_MORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasMore(Boolean hasMore) {
    this.hasMore = hasMore;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListMessageFilesResponse listMessageFilesResponse = (ListMessageFilesResponse) o;
    return Objects.equals(this._object, listMessageFilesResponse._object) &&
        Objects.equals(this.data, listMessageFilesResponse.data) &&
        Objects.equals(this.firstId, listMessageFilesResponse.firstId) &&
        Objects.equals(this.lastId, listMessageFilesResponse.lastId) &&
        Objects.equals(this.hasMore, listMessageFilesResponse.hasMore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_object, data, firstId, lastId, hasMore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListMessageFilesResponse {\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    firstId: ").append(toIndentedString(firstId)).append("\n");
    sb.append("    lastId: ").append(toIndentedString(lastId)).append("\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

