/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.model;

import java.util.Objects;
import java.util.Arrays;
import ch.lianto.openai.client.model.RunStepDetailsToolCallsCodeObject;
import ch.lianto.openai.client.model.RunStepDetailsToolCallsCodeObjectCodeInterpreter;
import ch.lianto.openai.client.model.RunStepDetailsToolCallsFunctionObject;
import ch.lianto.openai.client.model.RunStepDetailsToolCallsFunctionObjectFunction;
import ch.lianto.openai.client.model.RunStepDetailsToolCallsRetrievalObject;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RunStepDetailsToolCallsObjectToolCallsInner
 */
@JsonPropertyOrder({
  RunStepDetailsToolCallsObjectToolCallsInner.JSON_PROPERTY_ID,
  RunStepDetailsToolCallsObjectToolCallsInner.JSON_PROPERTY_TYPE,
  RunStepDetailsToolCallsObjectToolCallsInner.JSON_PROPERTY_CODE_INTERPRETER,
  RunStepDetailsToolCallsObjectToolCallsInner.JSON_PROPERTY_RETRIEVAL,
  RunStepDetailsToolCallsObjectToolCallsInner.JSON_PROPERTY_FUNCTION
})
@JsonTypeName("RunStepDetailsToolCallsObject_tool_calls_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-08T23:05:52.228713843+01:00[Europe/Zurich]")
public class RunStepDetailsToolCallsObjectToolCallsInner {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  /**
   * The type of tool call. This is always going to be &#x60;code_interpreter&#x60; for this type of tool call.
   */
  public enum TypeEnum {
    CODE_INTERPRETER("code_interpreter"),
    
    RETRIEVAL("retrieval"),
    
    FUNCTION("function");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_CODE_INTERPRETER = "code_interpreter";
  private RunStepDetailsToolCallsCodeObjectCodeInterpreter codeInterpreter;

  public static final String JSON_PROPERTY_RETRIEVAL = "retrieval";
  private Object retrieval;

  public static final String JSON_PROPERTY_FUNCTION = "function";
  private RunStepDetailsToolCallsFunctionObjectFunction function;

  public RunStepDetailsToolCallsObjectToolCallsInner() {
  }

  public RunStepDetailsToolCallsObjectToolCallsInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The ID of the tool call object.
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public RunStepDetailsToolCallsObjectToolCallsInner type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of tool call. This is always going to be &#x60;code_interpreter&#x60; for this type of tool call.
   * @return type
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public RunStepDetailsToolCallsObjectToolCallsInner codeInterpreter(RunStepDetailsToolCallsCodeObjectCodeInterpreter codeInterpreter) {
    
    this.codeInterpreter = codeInterpreter;
    return this;
  }

   /**
   * Get codeInterpreter
   * @return codeInterpreter
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE_INTERPRETER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RunStepDetailsToolCallsCodeObjectCodeInterpreter getCodeInterpreter() {
    return codeInterpreter;
  }


  @JsonProperty(JSON_PROPERTY_CODE_INTERPRETER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodeInterpreter(RunStepDetailsToolCallsCodeObjectCodeInterpreter codeInterpreter) {
    this.codeInterpreter = codeInterpreter;
  }


  public RunStepDetailsToolCallsObjectToolCallsInner retrieval(Object retrieval) {
    
    this.retrieval = retrieval;
    return this;
  }

   /**
   * For now, this is always going to be an empty object.
   * @return retrieval
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RETRIEVAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getRetrieval() {
    return retrieval;
  }


  @JsonProperty(JSON_PROPERTY_RETRIEVAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRetrieval(Object retrieval) {
    this.retrieval = retrieval;
  }


  public RunStepDetailsToolCallsObjectToolCallsInner function(RunStepDetailsToolCallsFunctionObjectFunction function) {
    
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RunStepDetailsToolCallsFunctionObjectFunction getFunction() {
    return function;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFunction(RunStepDetailsToolCallsFunctionObjectFunction function) {
    this.function = function;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RunStepDetailsToolCallsObjectToolCallsInner runStepDetailsToolCallsObjectToolCallsInner = (RunStepDetailsToolCallsObjectToolCallsInner) o;
    return Objects.equals(this.id, runStepDetailsToolCallsObjectToolCallsInner.id) &&
        Objects.equals(this.type, runStepDetailsToolCallsObjectToolCallsInner.type) &&
        Objects.equals(this.codeInterpreter, runStepDetailsToolCallsObjectToolCallsInner.codeInterpreter) &&
        Objects.equals(this.retrieval, runStepDetailsToolCallsObjectToolCallsInner.retrieval) &&
        Objects.equals(this.function, runStepDetailsToolCallsObjectToolCallsInner.function);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, codeInterpreter, retrieval, function);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RunStepDetailsToolCallsObjectToolCallsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    codeInterpreter: ").append(toIndentedString(codeInterpreter)).append("\n");
    sb.append("    retrieval: ").append(toIndentedString(retrieval)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

