/*
 * Ollama API
 * API Spec for Ollama API. Please see https://github.com/jmorganca/ollama/blob/main/docs/api.md for more details.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.ollama.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The response class for the generate endpoint.
 */
@JsonPropertyOrder({
  GenerateCompletionResponse.JSON_PROPERTY_MODEL,
  GenerateCompletionResponse.JSON_PROPERTY_CREATED_AT,
  GenerateCompletionResponse.JSON_PROPERTY_RESPONSE,
  GenerateCompletionResponse.JSON_PROPERTY_DONE,
  GenerateCompletionResponse.JSON_PROPERTY_CONTEXT,
  GenerateCompletionResponse.JSON_PROPERTY_TOTAL_DURATION,
  GenerateCompletionResponse.JSON_PROPERTY_LOAD_DURATION,
  GenerateCompletionResponse.JSON_PROPERTY_PROMPT_EVAL_COUNT,
  GenerateCompletionResponse.JSON_PROPERTY_PROMPT_EVAL_DURATION,
  GenerateCompletionResponse.JSON_PROPERTY_EVAL_COUNT,
  GenerateCompletionResponse.JSON_PROPERTY_EVAL_DURATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-06T00:48:30.515751098+01:00[Europe/Zurich]")
public class GenerateCompletionResponse {
  public static final String JSON_PROPERTY_MODEL = "model";
  private String model;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_RESPONSE = "response";
  private String response;

  public static final String JSON_PROPERTY_DONE = "done";
  private Boolean done;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  private List<Integer> context;

  public static final String JSON_PROPERTY_TOTAL_DURATION = "total_duration";
  private BigDecimal totalDuration;

  public static final String JSON_PROPERTY_LOAD_DURATION = "load_duration";
  private BigDecimal loadDuration;

  public static final String JSON_PROPERTY_PROMPT_EVAL_COUNT = "prompt_eval_count";
  private BigDecimal promptEvalCount;

  public static final String JSON_PROPERTY_PROMPT_EVAL_DURATION = "prompt_eval_duration";
  private BigDecimal promptEvalDuration;

  public static final String JSON_PROPERTY_EVAL_COUNT = "eval_count";
  private BigDecimal evalCount;

  public static final String JSON_PROPERTY_EVAL_DURATION = "eval_duration";
  private BigDecimal evalDuration;

  public GenerateCompletionResponse() {
  }

  public GenerateCompletionResponse model(String model) {
    
    this.model = model;
    return this;
  }

   /**
   * The model name.   Model names follow a &#x60;model:tag&#x60; format. Some examples are &#x60;orca-mini:3b-q4_1&#x60; and &#x60;llama2:70b&#x60;. The tag is optional and, if not provided, will default to &#x60;latest&#x60;. The tag is used to identify a specific version. 
   * @return model
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(String model) {
    this.model = model;
  }


  public GenerateCompletionResponse createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Date on which a model was created.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public GenerateCompletionResponse response(String response) {
    
    this.response = response;
    return this;
  }

   /**
   * The response for a given prompt with a provided model.
   * @return response
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResponse() {
    return response;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponse(String response) {
    this.response = response;
  }


  public GenerateCompletionResponse done(Boolean done) {
    
    this.done = done;
    return this;
  }

   /**
   * Whether the response has completed.
   * @return done
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDone() {
    return done;
  }


  @JsonProperty(JSON_PROPERTY_DONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDone(Boolean done) {
    this.done = done;
  }


  public GenerateCompletionResponse context(List<Integer> context) {
    
    this.context = context;
    return this;
  }

  public GenerateCompletionResponse addContextItem(Integer contextItem) {
    if (this.context == null) {
      this.context = new ArrayList<>();
    }
    this.context.add(contextItem);
    return this;
  }

   /**
   * An encoding of the conversation used in this response, this can be sent in the next request to keep a conversational memory. 
   * @return context
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getContext() {
    return context;
  }


  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContext(List<Integer> context) {
    this.context = context;
  }


  public GenerateCompletionResponse totalDuration(BigDecimal totalDuration) {
    
    this.totalDuration = totalDuration;
    return this;
  }

   /**
   * Time spent generating the response.
   * @return totalDuration
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTotalDuration() {
    return totalDuration;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalDuration(BigDecimal totalDuration) {
    this.totalDuration = totalDuration;
  }


  public GenerateCompletionResponse loadDuration(BigDecimal loadDuration) {
    
    this.loadDuration = loadDuration;
    return this;
  }

   /**
   * Time spent in nanoseconds loading the model.
   * @return loadDuration
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOAD_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLoadDuration() {
    return loadDuration;
  }


  @JsonProperty(JSON_PROPERTY_LOAD_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadDuration(BigDecimal loadDuration) {
    this.loadDuration = loadDuration;
  }


  public GenerateCompletionResponse promptEvalCount(BigDecimal promptEvalCount) {
    
    this.promptEvalCount = promptEvalCount;
    return this;
  }

   /**
   * Number of tokens in the prompt.
   * @return promptEvalCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMPT_EVAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPromptEvalCount() {
    return promptEvalCount;
  }


  @JsonProperty(JSON_PROPERTY_PROMPT_EVAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromptEvalCount(BigDecimal promptEvalCount) {
    this.promptEvalCount = promptEvalCount;
  }


  public GenerateCompletionResponse promptEvalDuration(BigDecimal promptEvalDuration) {
    
    this.promptEvalDuration = promptEvalDuration;
    return this;
  }

   /**
   * Time spent in nanoseconds evaluating the prompt.
   * @return promptEvalDuration
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMPT_EVAL_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPromptEvalDuration() {
    return promptEvalDuration;
  }


  @JsonProperty(JSON_PROPERTY_PROMPT_EVAL_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromptEvalDuration(BigDecimal promptEvalDuration) {
    this.promptEvalDuration = promptEvalDuration;
  }


  public GenerateCompletionResponse evalCount(BigDecimal evalCount) {
    
    this.evalCount = evalCount;
    return this;
  }

   /**
   * Number of tokens the response.
   * @return evalCount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getEvalCount() {
    return evalCount;
  }


  @JsonProperty(JSON_PROPERTY_EVAL_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvalCount(BigDecimal evalCount) {
    this.evalCount = evalCount;
  }


  public GenerateCompletionResponse evalDuration(BigDecimal evalDuration) {
    
    this.evalDuration = evalDuration;
    return this;
  }

   /**
   * Time in nanoseconds spent generating the response.
   * @return evalDuration
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVAL_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getEvalDuration() {
    return evalDuration;
  }


  @JsonProperty(JSON_PROPERTY_EVAL_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvalDuration(BigDecimal evalDuration) {
    this.evalDuration = evalDuration;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateCompletionResponse generateCompletionResponse = (GenerateCompletionResponse) o;
    return Objects.equals(this.model, generateCompletionResponse.model) &&
        Objects.equals(this.createdAt, generateCompletionResponse.createdAt) &&
        Objects.equals(this.response, generateCompletionResponse.response) &&
        Objects.equals(this.done, generateCompletionResponse.done) &&
        Objects.equals(this.context, generateCompletionResponse.context) &&
        Objects.equals(this.totalDuration, generateCompletionResponse.totalDuration) &&
        Objects.equals(this.loadDuration, generateCompletionResponse.loadDuration) &&
        Objects.equals(this.promptEvalCount, generateCompletionResponse.promptEvalCount) &&
        Objects.equals(this.promptEvalDuration, generateCompletionResponse.promptEvalDuration) &&
        Objects.equals(this.evalCount, generateCompletionResponse.evalCount) &&
        Objects.equals(this.evalDuration, generateCompletionResponse.evalDuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, createdAt, response, done, context, totalDuration, loadDuration, promptEvalCount, promptEvalDuration, evalCount, evalDuration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateCompletionResponse {\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    totalDuration: ").append(toIndentedString(totalDuration)).append("\n");
    sb.append("    loadDuration: ").append(toIndentedString(loadDuration)).append("\n");
    sb.append("    promptEvalCount: ").append(toIndentedString(promptEvalCount)).append("\n");
    sb.append("    promptEvalDuration: ").append(toIndentedString(promptEvalDuration)).append("\n");
    sb.append("    evalCount: ").append(toIndentedString(evalCount)).append("\n");
    sb.append("    evalDuration: ").append(toIndentedString(evalDuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

