/*
 * Ollama API
 * API Spec for Ollama API. Please see https://github.com/jmorganca/ollama/blob/main/docs/api.md for more details.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.ollama.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Request class for pushing a model.
 */
@JsonPropertyOrder({
  PushModelRequest.JSON_PROPERTY_NAME,
  PushModelRequest.JSON_PROPERTY_INSECURE,
  PushModelRequest.JSON_PROPERTY_STREAM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-06T00:48:30.515751098+01:00[Europe/Zurich]")
public class PushModelRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_INSECURE = "insecure";
  private Boolean insecure = false;

  public static final String JSON_PROPERTY_STREAM = "stream";
  private Boolean stream = false;

  public PushModelRequest() {
  }

  public PushModelRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the model to push in the form of &lt;namespace&gt;/&lt;model&gt;:&lt;tag&gt;.
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public PushModelRequest insecure(Boolean insecure) {
    
    this.insecure = insecure;
    return this;
  }

   /**
   * Allow insecure connections to the library.   Only use this if you are pushing to your library during development. 
   * @return insecure
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSECURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInsecure() {
    return insecure;
  }


  @JsonProperty(JSON_PROPERTY_INSECURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInsecure(Boolean insecure) {
    this.insecure = insecure;
  }


  public PushModelRequest stream(Boolean stream) {
    
    this.stream = stream;
    return this;
  }

   /**
   * If &#x60;false&#x60; the response will be returned as a single response object, otherwise the response will be streamed as a series of objects. 
   * @return stream
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getStream() {
    return stream;
  }


  @JsonProperty(JSON_PROPERTY_STREAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStream(Boolean stream) {
    this.stream = stream;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushModelRequest pushModelRequest = (PushModelRequest) o;
    return Objects.equals(this.name, pushModelRequest.name) &&
        Objects.equals(this.insecure, pushModelRequest.insecure) &&
        Objects.equals(this.stream, pushModelRequest.stream);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, insecure, stream);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushModelRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    insecure: ").append(toIndentedString(insecure)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

