/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.api;

import ch.lianto.openai.client.model.CreateEmbeddingRequest;
import ch.lianto.openai.client.model.CreateEmbeddingResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmbeddingsApi
 */
@Ignore
public class EmbeddingsApiTest {

    private final EmbeddingsApi api = new EmbeddingsApi();

    
    /**
     * Creates an embedding vector representing the input text.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEmbeddingTest() {
        CreateEmbeddingRequest createEmbeddingRequest = null;
        CreateEmbeddingResponse response = api.createEmbedding(createEmbeddingRequest);

        // TODO: test validations
    }
    
}
