/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.lianto.openai.client.api;

import ch.lianto.openai.client.model.CreateFineTuneRequest;
import ch.lianto.openai.client.model.FineTune;
import ch.lianto.openai.client.model.ListFineTuneEventsResponse;
import ch.lianto.openai.client.model.ListFineTunesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FineTunesApi
 */
@Ignore
public class FineTunesApiTest {

    private final FineTunesApi api = new FineTunesApi();

    
    /**
     * Immediately cancel a fine-tune job. 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelFineTuneTest() {
        String fineTuneId = null;
        FineTune response = api.cancelFineTune(fineTuneId);

        // TODO: test validations
    }
    
    /**
     * Creates a job that fine-tunes a specified model from a given dataset.  Response includes details of the enqueued job including job status and the name of the fine-tuned models once complete.  [Learn more about fine-tuning](/docs/guides/legacy-fine-tuning) 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFineTuneTest() {
        CreateFineTuneRequest createFineTuneRequest = null;
        FineTune response = api.createFineTune(createFineTuneRequest);

        // TODO: test validations
    }
    
    /**
     * Get fine-grained status updates for a fine-tune job. 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFineTuneEventsTest() {
        String fineTuneId = null;
        Boolean stream = null;
        ListFineTuneEventsResponse response = api.listFineTuneEvents(fineTuneId, stream);

        // TODO: test validations
    }
    
    /**
     * List your organization&#39;s fine-tuning jobs 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFineTunesTest() {
        ListFineTunesResponse response = api.listFineTunes();

        // TODO: test validations
    }
    
    /**
     * Gets info about the fine-tune job.  [Learn more about fine-tuning](/docs/guides/legacy-fine-tuning) 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveFineTuneTest() {
        String fineTuneId = null;
        FineTune response = api.retrieveFineTune(fineTuneId);

        // TODO: test validations
    }
    
}
