spring:
  shell:
    help:
      enabled: true
  flyway:
    enabled: false
  jackson:
    default-property-inclusion: non_empty
app:
  persistence:
    simple:
      file: file:/home/andre/apps/aiwiki/data-store.json
  openai:
    api-key: ${OPENAI_API_KEY}
    chat-model: "_3_5_TURBO"
    embedding-model: "text-embedding-ada-002"