app:
  persistence:
    simple:
      file: file:/home/andre/apps/aiwiki/gpt-3.5.json
  indexing:
    chunking: max_token
    enable-additional-embeddings: true
  openai:
    api-key: ${OPENAI_API_KEY}
    embedding-model: "_3_large"
    generation-model: "_4o"
  ollama:
    ollama-url: http://localhost:11434
    generation-model: "gemma:2b"
    embedding-model: "nomic-embed-text"
    prompt-prefixes:
      QUERY: "search_query:"
      DOCUMENT: "search_document:"

spring:
  shell:
    help:
      enabled: true
  flyway:
    enabled: false
  jackson:
    default-property-inclusion: non_empty
  profiles:
    group:
      openai:
        - openai-generation
        - openai-embeddings
      ollama:
        - ollama-generation
        - ollama-embeddings

logging:
  level:
    java.net: TRACE
    ch.lianto.openai.client: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG
  file:
    name: wiki.log